{% set version = "1.0.0" %}
package:
    name: e3sm_nex
    version: {{ version }}

source:
    git_rev: master
    git_url: git://github.com/cdat/e3sm_nex

build:
  number: 0
  noarch: python
  script: python setup.py install
 
requirements:
  build:
    - python
    - setuptools
    - requests
  run:
    - python
    - vcs

about:
    home:  http://gitub.com/cdat/e3sm_nex
    summary: A set of tools to use E3SM native grids

maintainers:
    doutriaux1

