package:
    name: e3sm_nex
    version: 0.0.1

source:
    git_rev: master
    git_url: git://github.com/cdat/e3sm_nex

build:
  number: 0
 
requirements:
  build:
    - python {{ python }}
    - setuptools
    - requests
  run:
    - python {{ python }}
    - cdms2
    - vcs

about:
    home:  http://gitub.com/UV-CDAT/cdutil



